package utils;

import com.aventstack.extentreports.ExtentTest;
import com.aventstack.extentreports.Status;
import org.testng.ITestContext;
import org.testng.ITestListener;
import org.testng.ITestResult;
import java.io.File;

public class TestListener implements ITestListener {

    @Override
    public void onStart(ITestContext context) {
        ExtentManager.getInstance();
    }

    @Override
    public void onTestStart(ITestResult result) {
        // Fetch the description from the @Test annotation if it exists
        String testDescription = result.getMethod().getDescription();
        String testName = (testDescription != null && !testDescription.isEmpty())
                ? testDescription
                : result.getMethod().getMethodName();

        ExtentTest test = ExtentManager.getInstance().createTest(testName);
        ExtentManager.setTest(test);
    }

    @Override
    public void onTestSuccess(ITestResult result) {
        ExtentManager.getTest().log(Status.PASS, "Test Passed Successfully");
    }

    @Override
    public void onTestFailure(ITestResult result) {
        ExtentManager.getTest().log(Status.FAIL, "Test Failed: " + result.getThrowable());

        // Locate the screenshot generated by your takeScreenshot method
        String screenshotPath = System.getProperty("user.dir") + File.separator + "screenshots" + File.separator + result.getName() + ".png";
        File screenshotFile = new File(screenshotPath);

        if (screenshotFile.exists()) {
            ExtentManager.getTest().addScreenCaptureFromPath(screenshotFile.getAbsolutePath(), "Failure Screenshot");
            System.out.println("🔗 Attached screenshot to Extent Report from: " + screenshotFile.getAbsolutePath());
        } else {
            System.out.println("⚠️ Warning: Screenshot file not found at " + screenshotPath);
        }
    }

    @Override
    public void onTestSkipped(ITestResult result) {
        ExtentManager.getTest().log(Status.SKIP, "Test Skipped");
    }

    @Override
    public void onFinish(ITestContext context) {
        if (ExtentManager.getInstance() != null) {
            ExtentManager.getInstance().flush();
            System.out.println("📊 Extent Report flushed and updated successfully!");
        }
    }
}