package pages.locators;

public enum ElementKey {

    // Permissions
    ALLOW_CONTACT_BUTTON,

    // Avatar
    CHANGE_AVATAR,
    UPLOAD_PHOTO,
    SELECT_USER_PHONE_PHOTO,
    DONE_BUTTON,
    SAVE_BUTTON,
    CANCEL_BUTTON,

    // Navigation
    NAVIGATE_BACK,
    SIGN_UP_BUTTON,
    // Continue
    CONTINUE_BUTTON,
    CONTINUE_BUTTON_ASSERTION,

    // Signup
    SIGNUP_FIELD,
    TERMS_CHECKBOX,
    FIRST_NAME_FIELD,
    LAST_NAME_FIELD,
    COUNTRY_DROPDOWN_FIELD,
    FINISH_BUTTON,

    // Authentication
    EMAIL_FIELD,
    PASSWORD_FIELD,
    VERIFICATION_FIELD,

    // Creation
    CANCEL_BUTTON_CREATION,
    SIGN_IN_BUTTON,
    YES_BUTTON,
    NO_BUTTON,
    // Gallery
    SCROLL_CONTAINER_LOCATOR,
    JUST_ONE_SELECT,
    OK_BUTTON
    ,USER_MENU
    ,LOGOUT_BUTTON,
    LOGOUT_CONFIRM
}